spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/edix?useSSL=false&serverTimezone=UTC
    username: root
    password: 5628
    driver-class-name: com.mysql.cj.jdbc.Driver
